// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhcbdzaammelnxcofazs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoY2JkemFhbW1lbG54Y29mYXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjU4NjEsImV4cCI6MjA2NzA0MTg2MX0.KbNEYu3a4QqW8jqH9u_Q3mxTKi_0JnikaKlsLOyQHz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});